basePath: /
definitions:
  main.AverageResult:
    properties:
      comment:
        type: string
      date:
        type: string
      result:
        type: number
    type: object
  main.ResponseError:
    properties:
      error:
        type: string
    type: object
  main.UserData:
    properties:
      values:
        items:
          type: integer
        type: array
    type: object
host: localhost:8081
info:
  contact: {}
  description: Это API для работы с пользовательскими данными BASFI.
  title: Swagger index BASFI API
  version: "1.0"
paths:
  /resultUser:
    get:
      description: Возвращает все расчеты BASFI, если данные были добавлены
      produces:
      - application/json
      responses:
        "200":
          description: Все расчеты BASFI
          schema:
            items:
              $ref: '#/definitions/main.AverageResult'
            type: array
        "404":
          description: 'Ошибка: Данные не найдены'
          schema:
            $ref: '#/definitions/main.ResponseError'
      summary: Получение всех расчетов BASFI
      tags:
      - Пользовательские данные
  /userData:
    post:
      consumes:
      - application/json
      description: Сохраняет данные пользователя и возвращает расчет BASFI
      parameters:
      - description: Массив из 10 чисел
        in: body
        name: userData
        required: true
        schema:
          $ref: '#/definitions/main.UserData'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное добавление с расчетом BASFI
          schema:
            $ref: '#/definitions/main.AverageResult'
        "400":
          description: 'Ошибка: Неверные данные'
          schema:
            $ref: '#/definitions/main.ResponseError'
      summary: Добавление данных пользователя BASFI
      tags:
      - Пользовательские данные
swagger: "2.0"
